#! /usr/bin/env python3
# -*- coding: UTF-8 -*-

import algos
from sys import exit
import helpers as h
from helpers import *

def main():
    als = algos.get_algos()

    width, algo, flags = h.read_args(als)

    if flags.ls:
        for alg in als.keys():
            print(alg)
        exit(0)

    if flags.info:
        name = flags.info
        if name not in als:
            h.unknown_algo_error(name, als)

        fun, sd = als[flags.info]
        h.print_algo_info(name, fun, sd)
        exit(0)

    if algo and algo not in als:
        h.unknown_algo_error(algo, als)

    fn, _ = als[algo]
    res = fn(read_words(), width)
    for line in res:
        if isinstance(line, str):
            print(line)
        else: # lists of words
            print(" ".join(line))


if __name__ == '__main__':
    main()
